apiVersion: v1
kind: Service
metadata:
  annotations: 
    metallb.universe.tf/allow-shared-ip: shared
  name: coredns-svc-lb-tcp
spec:
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns-metrics
    port: 9153
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 172.17.255.2

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  name: coredns-svc-lb-udp
spec:
  ports:
  - name: dns-udp
    port: 53
    protocol: UDP
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 172.17.255.2
