apiVersion: v1
kind: ServiceAccount
metadata:
  name: ken
  namespace: dev

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sa-dev-view
subjects:
- kind: ServiceAccount
  name: ken
  namespace: dev
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: ""
