apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  annotations:
          kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "web"        
    http:
      paths:
      - path: /web
        pathType: Prefix
        backend:
           service:
             name: web-svc
             port:
               number: 80
