repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: harbor
  url: https://helm.goharbor.io
- name: jetstack
  url: https://charts.jetstack.io
- name: chartmuseum
  url: https://chartmuseum.34.88.168.210.nip.io/

releases:
- name: nginx-ingress
  wait: true
  chart: stable/nginx-ingress
  namespace: nginx-ingress
  version: latest

- name: cert-manager
  wait: true
  chart: jetstack/cert-manager
  namespace: cert-manager
  version: latest

- name: chartmuseum
  wait: true
  chart: stable/chartmuseum
  namespace: chartmuseum
  version: latest
  values:
    - envs/values/chartmuseum.yaml

- name: harbor
  wait: true
  chart: harbor/harbor
  namespace: harbor
  version: latest
  values:
    - envs/values/harbor.yaml