apiVersion: apps/v1
kind: Deployment
metadata:
   name: paymentservice
   labels:
      app: paymentservice
      tier: paymentservice
spec:
   replicas: 3
   strategy:
           type: RollingUpdate
           rollingUpdate:
                   maxSurge: 100%
                   maxUnavailable: 0
   selector:
     matchLabels:
       tier: paymentservice      
   template:
     metadata:
       labels:
         app: paymentservice
         tier: paymentservice
     spec:
        containers:
        - name: server
          image: izhur85/pay-msdemo:v0.0.2
