apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: hipster-shop
  namespace: hipster-shop
spec:
  rules:
  - host: shop.34.88.168.210.nip.io
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: {{ .Values.service.port }}
        path: /
        pathType: Prefix
